# Generated by Django 3.0.4 on 2020-06-26 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogcomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogcomment',
            old_name='coment',
            new_name='comment',
        ),
    ]
